# This file was generated by GoReleaser. DO NOT EDIT.
cask "zlily" do
  version "0.9.8"

  on_macos do
    on_intel do
      sha256 "5aab18315896f8d8755ee48f2cb795198de0351399aac4cded1783d993dd96d2"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "44f373ac3e8bf1bde8450e96aae4adb844a52d6fdc0a578916ba5a24fd46e26c"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f14b7e75234a909dd3bc7e16b34f8d2fdd2d720a3ccc1decd36ad64acfdc4c6e"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f5ae7824ca2e3f8edb276ea956192a7c8b9baca497c009e8aa347028918afe71"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Linux_arm64.tar.gz"
    end
  end

  name "zlily"
  desc "Terminal UI client for the Lily chat server"
  homepage "https://github.com/joshw/zephyrlily"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zlily"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zlily"]
    end
  end

  # No zap stanza required

end
