# This file was generated by GoReleaser. DO NOT EDIT.
cask "zlily" do
  version "0.12.0"

  on_macos do
    on_arm do
      sha256 "a89c3d9f01f9245fcdfa88da5c1f9b96bb493c971954f8a3108373696289b42a"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "63fcb0a588824548350ebc931b7a3a0f64cdfd68304ea7f0af24b4eb62063f39"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a62080ca730280ea42a5f303c0992983c6eeb8090ae290738d96571b058283fe"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "79fe393c4ad89b92b1a9b0f874f80c38ca27dc08da67919550decd3feac44c6b"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Linux_x86_64.tar.gz"
    end
  end

  name "zlily"
  desc "Terminal UI client for the Lily chat server"
  homepage "https://github.com/joshw/zephyrlily"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zlily"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zlily"]
    end
  end

  # No zap stanza required
end
