# This file was generated by GoReleaser. DO NOT EDIT.
cask "zlily" do
  version "0.13.1"

  on_macos do
    on_arm do
      sha256 "d0b5a4a1c0c777137053faefa46544da14c64b8e33ac5ceb785b44aaaa64ec6e"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eeaddeea72211fd6c07e4d46f0c8751ae9ecebad11fe2242c559f638584b34f9"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "666b1be50e0741e38c06243b71e722ca7049d9594f4873bac4e35fcccadee1a0"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4a87d2a99cffa245f8364787f46d833371274d45abd6ad9bc63fcc95f588b8ed"
      url "https://github.com/joshw/zephyrlily/releases/download/v#{version}/zephyrlily_Linux_x86_64.tar.gz"
    end
  end

  name "zlily"
  desc "Terminal UI client for the Lily chat server"
  homepage "https://github.com/joshw/zephyrlily"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zlily"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/zlily"]
    end
  end

  # No zap stanza required
end
